require 'action_controller'
require 'action_view'
require 'action_view/helpers'
require 'action_view/helpers/asset_tag_helper'
require 'action_view/helpers/capture_helper'
require 'action_view/helpers/date_helper'
require 'action_view/helpers/form_helper'
require 'action_view/helpers/form_options_helper'
require 'action_view/helpers/form_tag_helper'
require 'action_view/helpers/javascript_helper'
require 'action_view/helpers/number_helper'
require 'action_view/helpers/prototype_helper'
require 'action_view/helpers/sanitize_helper'
require 'action_view/helpers/scriptaculous_helper'
require 'action_view/helpers/tag_helper'
require 'action_view/helpers/text_helper'
require 'action_view/helpers/url_helper'


include ActionView::Helpers::AssetTagHelper 
include ActionView::Helpers::CaptureHelper
include ActionView::Helpers::DateHelper
include ActionView::Helpers::DebugHelper
include ActionView::Helpers::FormHelper
include ActionView::Helpers::FormOptionsHelper
include ActionView::Helpers::FormTagHelper
include ActionView::Helpers::JavaScriptHelper
include ActionView::Helpers::NumberHelper
include ActionView::Helpers::PrototypeHelper
include ActionView::Helpers::SanitizeHelper
include ActionView::Helpers::ScriptaculousHelper
include ActionView::Helpers::TagHelper
include ActionView::Helpers::TextHelper
include ActionView::Helpers::UrlHelper